version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: pg_pass
      POSTGRES_USER: pguser
      POSTGRES_DB: measurements
    ports:
      - "5432:5432"